on:
  - push

jobs:
  run-vivliostyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Vivliostyle action
        uses: vivliostyle/action@v1
        with:
          cli-version: 5.5.1
          input: vivliostyle.config.js
          if-no-files-found: error
